server:
  port: 7970

spring:
  application:
    name: tx-manager
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:9527/tx-manager?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8&nullCatalogMeansCurrent=true&useSSL=false
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password:

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true

tx-lcn:
  manager:
    host: 127.0.0.1 # TxManager Host Ip
    port: 8070 # TxClient连接请求端口
    heart-time: 15000 # 心跳检测时间(ms)
    dtx-time: 30000 # 分布式事务执行总时间
    concurrent-level: 128
    admin-key: 123456 # TM后台登陆密码，默认值为codingapi
  message:
    netty.attr-delay-time: 10000 #参数延迟删除时间单位ms
  logger:
    enabled: true # 开启日志,默认为false
    driver-class-name: ${spring.datasource.driver-class-name}
    jdbc-url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}

logging:
  level:
    com:
      codingapi: debug